#!/usr/bin/env python3
"""
poisoning_pct_comparison.py — Main baselines across poisoning severity (results_old).

Reads results_old/{10,20,30}pct/results/all_experiments_results.csv and, for
each poisoning percentage, computes the mean test metric of each of the six
main baselines:

    Clean, Baseline, Saga++, CP, Curriculum, QuAIL

Only each config's best hyperparameter trial (rank == 1 in the CSV, i.e. the
optuna best_trial — same convention as elo_ratings.py / quail_analysis.py) is
used, across every dataset and seed. AR and NAR (the two label-poisoning noise
modes) are kept separate, since they were generated by different corruption
processes and are not comparable 1:1; Clean has no noise mode and is repeated
identically on both panels as a fixed reference.

Also supports comparing training cost instead of a performance metric
(--metric wall_time / cpu_time). This drops the Clean bar (clean has no
poisoning to defend against, so it isn't a cost competitor) and computes
total time the same way the earlier mlp_{noise}_time_pct.png plots did:

    total = external preprocessing time (Saga++/CP's heavy one-off cleaning
            script, read from data_cleaned_saga|cp/metrics/*_perf_metrics.csv)
          + in-process preproc_{cpu,wall}_time (every config, from the CSV)
          + training {cpu,wall}_time (from the CSV)

Note: results_old has no per-percentage archive of that external
preprocessing cost — only one current data_cleaned_saga/data_cleaned_cp
snapshot exists on disk. It is added identically to Saga++/CP at all three
percentages (per user decision), so it does not vary with severity even
though the in-CSV components do. Each bar's parenthetical is its percentage
of the slowest method in that same (pct, noise mode) group, and the fastest
method per group is the one highlighted in green.

Usage
-----
    python poisoning_pct_comparison.py
    python poisoning_pct_comparison.py --metric accuracy
    python poisoning_pct_comparison.py --metric wall_time
"""

import argparse
import re
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch
import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
RESULTS_OLD = HERE.parent / "results_old"
PLOTS_DIR = HERE / "plots"

PCTS = [10, 20, 30, 40]
NOISE_MODES = ["ar", "nar"]
NOISE_MODE_LABELS = {"ar": "CCAR (AR)", "nar": "CNAR (NAR)"}

# Fixed display order + validated categorical palette (dataviz skill:
# scripts/validate_palette.js reports ALL CHECKS PASS on this 6-slot set,
# worst adjacent CVD ΔE 24.2). Order is the CVD-safety mechanism, not
# cosmetic — keep it as-is if you add/remove a category.
CATEGORY_ORDER = ["clean", "baseline", "saga++", "cp", "curriculum", "quail"]
CATEGORY_LABELS = {
    "clean": "Clean",
    "baseline": "Standard",
    "saga++": "Saga++",
    "cp": "CP",
    "curriculum": "Curriculum",
    "quail": "QuAIL",
}
CATEGORY_COLORS = {
    "clean": "#2a78d6",
    "baseline": "#1baf7a",
    "saga++": "#eda100",
    "cp": "#eb6834",
    "curriculum": "#4a3aa7",
    "quail": "#e34948",
}

# Metric registry. Score metrics (kind="score") read one CSV column directly.
# Cost metrics (kind="time") sum the in-process preproc + training columns
# and then have the matching external Saga++/CP preprocessing cost added in
# main(); they also drop Clean and switch the bar annotation from "gap to
# Clean" to "% of the slowest method" (see _load_external_preproc_times).
# `bounded` caps the zoomed y-axis at 1.0 (only meaningful for [0, 1] scores).
# `lower_better` flips which bar is "best" (highlighted green): highest score
# vs. lowest cost.
METRIC_SPECS = {
    "f1":        dict(kind="score", col="test_f1",        label="test f1",             dec=3, bounded=True,  lower_better=False, drop_clean=False),
    "accuracy":  dict(kind="score", col="test_accuracy",  label="test accuracy",       dec=3, bounded=True,  lower_better=False, drop_clean=False),
    "auc":       dict(kind="score", col="test_auc",       label="test auc",            dec=3, bounded=True,  lower_better=False, drop_clean=False),
    "precision": dict(kind="score", col="test_precision", label="test precision",      dec=3, bounded=True,  lower_better=False, drop_clean=False),
    "recall":    dict(kind="score", col="test_recall",    label="test recall",         dec=3, bounded=True,  lower_better=False, drop_clean=False),
    "wall_time": dict(kind="time", preproc_col="preproc_wall_time", train_col="wall_time",
                       ext_key="wall_time_s", label="total wall-clock time (s)", dec=2, bounded=False, lower_better=True, drop_clean=True),
    "cpu_time":  dict(kind="time", preproc_col="preproc_cpu_time", train_col="cpu_time",
                       ext_key="cpu_time_s",  label="total CPU time (s)",       dec=2, bounded=False, lower_better=True, drop_clean=True),
}

# External one-off preprocessing cost for Saga++/CP (see module docstring):
# {(dataset, data_mode, category): {"cpu_time_s": ..., "wall_time_s": ...}}
_EXTERNAL_PREPROC_DIRS = {
    "saga++": HERE.parent / "data_cleaned_saga",
    "cp":     HERE.parent / "data_cleaned_cp",
}


def _load_external_preproc_times() -> dict:
    lookup = {}
    for category, base_dir in _EXTERNAL_PREPROC_DIRS.items():
        metrics_dir = base_dir / "metrics"
        if not metrics_dir.exists():
            continue
        for csv_path in metrics_dir.glob("*_perf_metrics.csv"):
            stem = csv_path.stem.replace("_perf_metrics", "")
            data_mode = None
            for mode in ("nar", "ar"):  # nar first so "ar" doesn't match inside "nar"
                if stem.endswith(f"_{mode}"):
                    dataset = re.sub(r"^\d+_\d+_", "", stem[: -len(f"_{mode}")])
                    data_mode = mode
                    break
            if data_mode is None:
                continue
            dfp = pd.read_csv(csv_path)
            if not {"cpu_time_s", "wall_time_s"}.issubset(dfp.columns):
                continue
            lookup[(dataset, data_mode, category)] = {
                "cpu_time_s":  float(dfp["cpu_time_s"].mean()),
                "wall_time_s": float(dfp["wall_time_s"].mean()),
            }
    return lookup

# Status green (reserved — never a categorical hue) used only to flag the
# best-performing non-clean method per group, so "best" is a status overlay
# rather than repainting a bar's identity color.
BEST_COLOR = "#0ca30c"
INK_PRIMARY = "#0b0b0b"
INK_MUTED = "#6b6a65"
CLEAN_LINE_COLOR = "#898781"


def _categorize(row) -> str | None:
    """Map one CSV row to one of the six main baselines, or None to drop it
    (e.g. rank > 1 trials are filtered out earlier; anything else unmatched
    here is a config outside the six, like the +quail+curriculum combo)."""
    if row["data_mode"] == "clean":
        return "clean"
    if row["preparation"] == "saga":
        return "saga++"
    if row["preparation"] == "cp":
        return "cp"
    if row["preparation"] == "standard" and row["use_curriculum"] and not row["use_gate"]:
        return "curriculum"
    if row["preparation"] == "standard" and row["use_gate"] and not row["use_curriculum"]:
        return "quail"
    if row["preparation"] == "standard" and not row["use_curriculum"] and not row["use_gate"]:
        return "baseline"
    return None


def load_pct(pct: int, spec: dict) -> pd.DataFrame:
    """Load one pct folder's CSV and compute a metric-agnostic `value` column:
    the raw score column for kind="score", or preproc+train time for
    kind="time" (external Saga++/CP cost is added later, in main(), since
    that lookup isn't per-pct)."""
    csv_path = RESULTS_OLD / f"{pct}pct" / "results" / "all_experiments_results.csv"
    base_cols = ["dataset", "data_mode", "model_type", "use_curriculum", "use_gate",
                 "preparation", "rank", "seed"]
    if spec["kind"] == "score":
        usecols = base_cols + [spec["col"]]
    else:
        usecols = base_cols + [spec["preproc_col"], spec["train_col"]]
    df = pd.read_csv(csv_path, usecols=usecols)
    df = df[(df["model_type"] == "mlp") & (df["rank"] == 1)].copy()
    df["category"] = df.apply(_categorize, axis=1)
    df = df[df["category"].notna()].copy()
    df["pct"] = pct
    if spec["kind"] == "score":
        df["value"] = df[spec["col"]]
    else:
        df["value"] = df[spec["preproc_col"]] + df[spec["train_col"]]
    return df


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--metric", default="f1", choices=list(METRIC_SPECS),
                     help="Which quantity to average per baseline (default: f1). "
                          "wall_time/cpu_time compare training cost instead of a score.")
    args = ap.parse_args()
    metric = args.metric
    spec = METRIC_SPECS[metric]
    dec = spec["dec"]
    lower_better = spec["lower_better"]
    drop_clean = spec["drop_clean"]

    df = pd.concat([load_pct(pct, spec) for pct in PCTS], ignore_index=True)
    print(f"Loaded {len(df)} rows (rank==1, mlp only) across pct={PCTS} | metric: {metric}")

    if spec["kind"] == "time":
        ext_lookup = _load_external_preproc_times()
        ext_key = spec["ext_key"]

        def _external(row):
            ext = ext_lookup.get((row["dataset"], row["data_mode"], row["category"]))
            return ext[ext_key] if ext else 0.0

        df["value"] = df["value"] + df.apply(_external, axis=1)

    means = (
        df.groupby(["pct", "data_mode", "category"])["value"]
        .mean()
        .reset_index()
    )

    cats_to_plot = [c for c in CATEGORY_ORDER if not (drop_clean and c == "clean")]
    n_cats = len(cats_to_plot)
    bar_width = 0.96 / n_cats
    x_base = np.arange(len(PCTS)).astype(float) * 1.22
    group_half_width = (n_cats * bar_width) / 2 + 0.04
    non_clean = [c for c in cats_to_plot if c != "clean"]

    # height_grid[noise_mode][cat] -> list of values, one per pct (NaN if missing)
    height_grid = {}
    for noise_mode in NOISE_MODES:
        height_grid[noise_mode] = {}
        for cat in cats_to_plot:
            vals = []
            for pct in PCTS:
                if cat == "clean":
                    sub = means[(means["pct"] == pct) & (means["category"] == "clean")]
                else:
                    sub = means[(means["pct"] == pct) & (means["data_mode"] == noise_mode)
                                 & (means["category"] == cat)]
                vals.append(sub["value"].iloc[0] if len(sub) else np.nan)
            height_grid[noise_mode][cat] = vals

    all_vals = [v for nm in height_grid.values() for vals in nm.values() for v in vals if pd.notna(v)]
    data_min, data_max = min(all_vals), max(all_vals)
    span = data_max - data_min
    y_lo = max(0.0, data_min - span * 0.05)
    y_hi = min(1.0, data_max + span * 0.32) if spec["bounded"] else data_max + span * 0.32

    PANEL_BG = "white"
    BAR_RADIUS_PX = 4.0  # visual corner radius, in pixels — matches across
                          # every panel/metric regardless of data scale

    fig = plt.figure(figsize=(12, 13.5), dpi=200, facecolor="white")
    gs = fig.add_gridspec(2, 1, height_ratios=[1, 1], hspace=0.10, top=0.89, bottom=0.12)
    ax_ar = fig.add_subplot(gs[0])
    ax_nar = fig.add_subplot(gs[1], sharex=ax_ar, sharey=ax_ar)
    bar_axes = {"ar": ax_ar, "nar": ax_nar}

    x_lo = x_base[0] - group_half_width - 0.15
    x_hi = x_base[-1] + group_half_width + 0.15

    # ---- upper/lower bar panels: CCAR (AR) then CNAR (NAR) ----
    for noise_mode in NOISE_MODES:
        ax = bar_axes[noise_mode]
        grid = height_grid[noise_mode]
        ax.set_facecolor(PANEL_BG)
        ax.set_xlim(x_lo, x_hi)
        ax.set_ylim(y_lo, y_hi)

        # convert a fixed on-screen pixel radius into (asymmetric) data units
        # so every bar gets the same *visual* rounding, however distorted
        # the x vs. y data scale is (score metrics span ~0-1, cost metrics
        # span ~0-200)
        bbox = ax.get_position()
        ax_w_px = bbox.width * fig.get_figwidth() * fig.dpi
        ax_h_px = bbox.height * fig.get_figheight() * fig.dpi
        data_per_px_x = (x_hi - x_lo) / ax_w_px
        data_per_px_y = (y_hi - y_lo) / ax_h_px
        corner_rx = BAR_RADIUS_PX * data_per_px_x
        corner_aspect = data_per_px_y / data_per_px_x

        def _rounded_bar(xpos, h, width, color, edgecolor, linewidth, zorder):
            # box starts at y=0 (the true baseline): the bottom two rounded
            # corners land far below the visible y_lo and get clipped by the
            # axes, leaving a flat/square baseline with only the top rounded
            ax.add_patch(FancyBboxPatch(
                (xpos - width / 2, 0.0), width, h,
                boxstyle=f"round,pad=0,rounding_size={corner_rx}",
                mutation_aspect=corner_aspect,
                linewidth=linewidth, edgecolor=edgecolor, facecolor=color,
                zorder=zorder, clip_on=True))

        for j, pct in enumerate(PCTS):
            clean_h = grid["clean"][j] if not drop_clean else None
            # best method for this (pct, noise_mode) group — lowest value for
            # cost metrics (time), highest for performance metrics; "worst"
            # (only used for the %-of-slowest annotation on cost metrics) is
            # always the opposite extreme
            candidates = {c: grid[c][j] for c in non_clean if pd.notna(grid[c][j])}
            if candidates:
                best_cat = min(candidates, key=candidates.get) if lower_better else max(candidates, key=candidates.get)
                worst_val = max(candidates.values()) if lower_better else min(candidates.values())
            else:
                best_cat = None
                worst_val = None

            # dashed reference line at the Clean level, spanning the group
            if not drop_clean and pd.notna(clean_h):
                ax.plot([x_base[j] - 0.42, x_base[j] + 0.42], [clean_h, clean_h],
                        linestyle=(0, (4, 2)), linewidth=1.2, color=CLEAN_LINE_COLOR,
                        zorder=1)

            for i, cat in enumerate(cats_to_plot):
                h = grid[cat][j]
                if pd.isna(h):
                    continue
                offset = (i - (n_cats - 1) / 2) * bar_width
                xpos = x_base[j] + offset
                is_best = (cat == best_cat)

                _rounded_bar(xpos, h, bar_width * 0.96,
                             color=CATEGORY_COLORS[cat],
                             edgecolor=BEST_COLOR if is_best else "none",
                             linewidth=2.4 if is_best else 0,
                             zorder=3 if cat == "quail" else 2)

                label_color = BEST_COLOR if is_best else INK_PRIMARY
                ax.text(xpos, h + span * 0.03, f"{h:.{dec}f}", rotation=90,
                        ha="center", va="bottom", fontsize=7.2,
                        fontweight="bold" if is_best else "normal",
                        color=label_color, zorder=4)

                if drop_clean and worst_val:
                    pct_of_worst = h / worst_val * 100.0
                    ax.text(xpos, h + span * 0.175, f"({pct_of_worst:.0f}%)", rotation=90,
                            ha="center", va="bottom", fontsize=6.3,
                            color=label_color if is_best else INK_MUTED, zorder=4)
                elif not drop_clean and cat != "clean" and pd.notna(clean_h):
                    delta = h - clean_h
                    ax.text(xpos, h + span * 0.175, f"({delta:+.{dec}f})", rotation=90,
                            ha="center", va="bottom", fontsize=6.3,
                            color=label_color if is_best else INK_MUTED, zorder=4)

        noise_short = NOISE_MODE_LABELS[noise_mode].split(" ")[0]
        ax.set_xticks(x_base)
        ax.set_xticklabels([f"{p}%" for p in PCTS], fontsize=10)
        ax.set_xlabel(f"Poisoning percentage ({noise_short})", fontsize=10.5)
        ax.set_xlim(x_lo, x_hi)
        ax.set_ylim(y_lo, y_hi)
        ax.set_ylabel(f"Mean {spec['label']}", fontsize=10)
        ax.grid(axis="y", linewidth=0.4, alpha=0.4, zorder=0)
        ax.set_axisbelow(True)
        for side in ("top", "right", "left"):
            ax.spines[side].set_visible(False)
        ax.tick_params(axis="y", length=0)
        ax.tick_params(axis="x", length=0)

    handles = [plt.Rectangle((0, 0), 1, 1, color=CATEGORY_COLORS[c]) for c in cats_to_plot]
    labels = [CATEGORY_LABELS[c] for c in cats_to_plot]
    if not drop_clean:
        handles.append(plt.Line2D([0], [0], linestyle=(0, (4, 2)), color=CLEAN_LINE_COLOR, linewidth=1.2))
        labels.append("Clean reference")
    best_legend = "Fastest method" if drop_clean else ("Fastest non-clean method" if lower_better else "Best non-clean method")
    handles.append(plt.Rectangle((0, 0), 1, 1, facecolor="none", edgecolor=BEST_COLOR, linewidth=2.4))
    labels.append(best_legend)
    fig.legend(handles, labels, loc="upper center", ncol=4,
               bbox_to_anchor=(0.5, 0.055), frameon=False, fontsize=9.5,
               handletextpad=0.6, columnspacing=1.5)

    if drop_clean:
        subtitle = "value above each bar; (%) = that bar's share of the slowest method's time"
    else:
        subtitle = "value above each bar; (Δ) = gap to Clean at that severity"
    fig.suptitle(f"Main baselines vs. poisoning severity — mean {spec['label']}\n{subtitle}",
                 fontsize=14, fontweight="bold", y=0.985)

    PLOTS_DIR.mkdir(exist_ok=True)
    out = PLOTS_DIR / f"poisoning_pct_comparison_{metric}.png"
    plt.savefig(out, bbox_inches="tight")
    print(f"Saved: {out}")
    plt.close()


if __name__ == "__main__":
    main()
